<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="4" errors="2" failures="0" skip="0"><testcase classname="src.testcase.testSearchPage.TestSearchPage" name="testSearch" time="0.009"><error type="builtins.TypeError" message="open_url() takes 1 positional argument but 2 were given"><![CDATA[Traceback (most recent call last):
  File "c:\python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\python36\lib\unittest\case.py", line 601, in run
    testMethod()
  File "c:\python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\app\hysc\src\testcase\testSearchPage.py", line 39, in testSearch
    baidu_page.open_url(url)
TypeError: open_url() takes 1 positional argument but 2 were given
]]></error><system-out><![CDATA[Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

]]></system-out><system-err><![CDATA[Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x0000000003B2CBE0>>
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
    self.stop()
  File "c:\python36\lib\site-packages\selenium\webdriver\common\service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
]]></system-err></testcase><testcase classname="src.testcase.testSearchPage.TestSearchPage" name="testSearch" time="0.012"><error type="builtins.AttributeError" message="'NoneType' object has no attribute 'quit'"><![CDATA[Traceback (most recent call last):
  File "c:\python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\python36\lib\unittest\case.py", line 604, in run
    self.tearDown()
  File "c:\python36\lib\site-packages\nose\case.py", line 385, in tearDown
    try_run(self.inst, ('teardown', 'tearDown'))
  File "c:\python36\lib\site-packages\nose\util.py", line 471, in try_run
    return func()
  File "D:\app\hysc\src\testcase\testSearchPage.py", line 60, in tearDown
    self.driver.quit()
AttributeError: 'NoneType' object has no attribute 'quit'
]]></error><system-out><![CDATA[Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

]]></system-out><system-err><![CDATA[Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x0000000003B2CBE0>>
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
    self.stop()
  File "c:\python36\lib\site-packages\selenium\webdriver\common\service.py", line 135, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
]]></system-err></testcase><testcase classname="src.testcase.testmycase.testMyCase" name="testcase" time="0.003"><system-out><![CDATA[setup function
com.example.android.apis
teardown function
]]></system-out></testcase><testcase classname="src.testcase.testmycase.testMyCase" name="testcase2" time="0.003"><system-out><![CDATA[setup function
com.example.android.apis
teardown function
]]></system-out></testcase></testsuite>